services:
  mlflow:
    build: .
    container_name: mlflow
    ports:
      - "5001:5000"     # UI dostępne na http://localhost:5001
    command: >
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --default-artifact-root /mlflow/artifacts
    environment:
      # Przyda się wewnątrz kontenera (np. dla CLI), ale i tak ustawimy w Twoim kodzie.
      - MLFLOW_TRACKING_URI=http://localhost:5000
    volumes:
      - ./mlflow_data:/mlflow
    restart: unless-stopped
